// <auto-generated />
using System;
using ILIS.Newton.Assignment.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ILIS.Newton.Assignment.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ILIS.Newton.Assignment.Entities.Entities.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Developer = "Nintendo",
                            Genre = "Adventure",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(1986, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Legend of Zelda"
                        },
                        new
                        {
                            Id = 2,
                            Developer = "CD Projekt Red",
                            Genre = "RPG",
                            Price = 49.99m,
                            ReleaseDate = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 3,
                            Developer = "GSC Game World",
                            Genre = "Survival",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2024, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Stalker 2: Heart of Chornobyl"
                        },
                        new
                        {
                            Id = 4,
                            Developer = "CD Projekt Red",
                            Genre = "RPG",
                            Price = 39.99m,
                            ReleaseDate = new DateTime(2015, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 5,
                            Developer = "Sucker Punch Productions",
                            Genre = "Action",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2020, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ghost of Tsushima"
                        },
                        new
                        {
                            Id = 6,
                            Developer = "Bethesda Game Studios",
                            Genre = "RPG",
                            Price = 29.99m,
                            ReleaseDate = new DateTime(2015, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fallout 4"
                        },
                        new
                        {
                            Id = 7,
                            Developer = "FromSoftware",
                            Genre = "RPG",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 8,
                            Developer = "Guerrilla Games",
                            Genre = "Action",
                            Price = 49.99m,
                            ReleaseDate = new DateTime(2017, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Horizon Zero Dawn"
                        },
                        new
                        {
                            Id = 9,
                            Developer = "Rockstar Games",
                            Genre = "Adventure",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 10,
                            Developer = "Santa Monica Studio",
                            Genre = "Action",
                            Price = 49.99m,
                            ReleaseDate = new DateTime(2018, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "God of War"
                        },
                        new
                        {
                            Id = 11,
                            Developer = "Ubisoft",
                            Genre = "RPG",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Assassin's Creed Valhalla"
                        },
                        new
                        {
                            Id = 12,
                            Developer = "BioWare",
                            Genre = "RPG",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2021, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mass Effect: Legendary Edition"
                        },
                        new
                        {
                            Id = 13,
                            Developer = "FromSoftware",
                            Genre = "RPG",
                            Price = 39.99m,
                            ReleaseDate = new DateTime(2016, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dark Souls III"
                        },
                        new
                        {
                            Id = 14,
                            Developer = "Naughty Dog",
                            Genre = "Action",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2020, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Last of Us Part II"
                        },
                        new
                        {
                            Id = 15,
                            Developer = "Blizzard Entertainment",
                            Genre = "RPG",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2023, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Diablo IV"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
